export const products = [
    {
        id: 1,
        title: "Cerveza Rubia",
        price: 800,
        stock: 7,
        description: "La mejor cerveza rubia",
        category: "rubias",
        img: "https://res.cloudinary.com/dhuzq4kal/image/upload/v1678503918/rubia_vcuc0c.jpg",
    },
    {
        id: 2,
        title: "Cerveza Roja",
        price: 1000,
        stock: 5,
        description: "La mejor cerveza roja",
        category: "rojas",
        img: "https://res.cloudinary.com/dhuzq4kal/image/upload/v1678503918/roja_eytdqy.jpg",
    },
    {
        id: 3,
        title: "Cerveza Negra",
        price: 1200,
        stock: 4,
        description: "La mejor cerveza negra",
        category: "negras",
        img: "https://res.cloudinary.com/dhuzq4kal/image/upload/v1678503918/negra_uu6rjt.jpg",
    },
    {
        id: 4,
        title: "Cerveza Rubia 2",
        price: 770,
        stock: 6,
        description: "La segunda mejor cerveza rubia",
        category: "rubias",
        img: "https://res.cloudinary.com/dhuzq4kal/image/upload/v1678503918/rubia_vcuc0c.jpg",
    },
    {
        id: 5,
        title: "Cerveza Roja 2",
        price: 880,
        stock: 10,
        description: "La segunda mejor cerveza roja",
        category: "rojas",
        img: "https://res.cloudinary.com/dhuzq4kal/image/upload/v1678503918/roja_eytdqy.jpg",
    },
    {
        id: 6,
        title: "Cerveza Negra 2",
        price: 1110,
        stock: 3,
        description: "La segunda mejor cerveza negra",
        category: "negras",
        img: "https://res.cloudinary.com/dhuzq4kal/image/upload/v1678503918/negra_uu6rjt.jpg",
    },
    
]